apiVersion: v1
kind: Service
metadata:
  name: gateway
  namespace: filedepot
spec:
  type: {{ .Values.service.type }}
  selector:
    app: gateway
  ports:
    - protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: 8000
