apiVersion: apps/v1
kind: Deployment
metadata:
  name: file
  namespace: filedepot
  labels:
    app: file
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: file
  template:
    metadata:
      labels:
        app: file
    spec:
      containers:
        - name: file
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          envFrom:
            - configMapRef:
                name: filedepot-env
          ports:
            - containerPort: 8001
          readinessProbe:
            httpGet:
              path: /ping
              port: 8001
            initialDelaySeconds: 3
            periodSeconds: 5
            failureThreshold: 3
          livenessProbe:
            httpGet:
              path: /ping
              port: 8001
            initialDelaySeconds: 10
            periodSeconds: 10
            failureThreshold: 5
