apiVersion: v1
kind: Service
metadata:
  name: file
  namespace: filedepot
spec:
  type: {{ .Values.service.type }}
  selector:
    app: file
  ports:
    - protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: 8001
